### ISSUE TITLE
include usage instructions

### ISSUE THREAD

**Issue by matkoniecz** [sembruk/osm2xmap#2]
Some are visible after running the compiled program but even then what is "symbol set XMAP file" and how one may get it is unclear...

**Comment by matkoniecz** [comment]
> symbol set XMAP file

is it one of files residing in /usr/share/openorienteering-mapper/symbol sets/? But these files have omap extension...

http://www.openorienteering.org/api-docs/mapper/classSymbolSetTool.html suggests that xmap and omap are related.

Experimentation suggests that these files are not equivalent - using ISSOM_5000.omap as symbols.xmap resulted in `Segmentation fault (core dumped)`

**Comment by sembruk** [comment]
Added some information.

```
$ ./osm2xmap -h
Usage:
    ./osm2xmap [options]
    Options:
        -i filename - input OSM filename;
        -o filename - output XMAP filename;
        -s filename - symbol set XMAP or OMAP filename (see /usr/share/openorienteering-mapper/symbol\ sets/);
        -r filename - XML rules filename;
        --help, -h or help - this usage.

```

It work with *.xmap and *.omap symbol set files.

**Comment by sembruk** [comment]
> using ISSOM_5000.omap as symbols.xmap resulted in `Segmentation fault (core dumped)`

At what point it breaks down?

```
$ ./osm2xmap -s /usr/share/openorienteering-mapper/symbol\ sets/5000/ISSOM_5000.omap 
Using files:
    * input OSM file       - ./in.osm
    * output XMAP file     - ./out.xmap
    * symbol set XMAP file - /usr/share/openorienteering-mapper/symbol sets/5000/ISSOM_5000.omap
    * rules file           - ./rules.xml
Using georeferencing:
    mapScale           0.200000
    declination        0.000000
    grivation          0.000000
    mapRefPoint        (0.000000, 0.000000)
    projectedRefPoint  (428789.071810, 6266532.674917)
    geographicRefPoint (37.842050, 56.537750)
    projectedCrsDesc   '+proj=utm +datum=WGS84 +zone=37'
    geographicCrsDesc  '+proj=latlong +datum=WGS84'
Loading rules 'ISOM2000 adapeted for cyclogaine'... 
WARNING: Symbol with code 401 didn't find
<...>
WARNING: Symbol with code 998 didn't find
Ok
Converting nodes...
Ok
Converting ways...
Ok
Converting relations...
WARNING: Way 37751408 didn't find
<...>
WARNING: Way 75589035 didn't find
Ok

Execution time: 2.000000 sec.
```

These warnings are normal.

**Comment by matkoniecz** [comment]
> At what point it breaks down?

It appears to depend on data. I am trying to reproduce it with small amount of data, for now I encountered a separate bug (reported as #4).

**Comment by matkoniecz** [comment]
fatal error on UTF-8 reported is as #5
